# Generated by Django 3.0.7 on 2021-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullyearconsolidated18',
            name='ADBRST42',
            field=models.CharField(max_length=3, verbose_name='SAQ: HAVE BRST CANCER BRST REMOVED'),
        ),
        migrations.AlterField(
            model_name='populationcharacteristics18',
            name='ADBRST42',
            field=models.CharField(max_length=3, verbose_name='SAQ: HAVE BRST CANCER BRST REMOVED'),
        ),
    ]
