from .dental_visits_models import (
    DentalVisits18,
    DentalVisits17,
    DentalVisits16,
    DentalVisits15,
    DentalVisits14,
    DentalVisits13,
    DentalVisits12,
    DentalVisits11,
    DentalVisits10,
    DentalVisits09,
    DentalVisits08,
    DentalVisits07,
    DentalVisits06,
    DentalVisits05,
)

from .emergency_room_visits_models import (
    EmergencyRoomVisits18,
    EmergencyRoomVisits17,
    EmergencyRoomVisits16,
    EmergencyRoomVisits15,
    EmergencyRoomVisits14,
    EmergencyRoomVisits13,
    EmergencyRoomVisits12,
    EmergencyRoomVisits11,
    EmergencyRoomVisits10,
    EmergencyRoomVisits09,
    EmergencyRoomVisits08,
    EmergencyRoomVisits07,
    EmergencyRoomVisits06,
    EmergencyRoomVisits05,
)

from .full_year_consolidated_models import (
    FullYearConsolidated18,
    FullYearConsolidated17,
    FullYearConsolidated16,
    FullYearConsolidated15,
    FullYearConsolidated14,
    FullYearConsolidated13,
    FullYearConsolidated12,
    FullYearConsolidated11,
    FullYearConsolidated10,
    FullYearConsolidated09,
    FullYearConsolidated08,
    FullYearConsolidated07,
    FullYearConsolidated06,
    FullYearConsolidated05,
)

from .home_health_models import (
    HomeHealth18,
    HomeHealth17,
    HomeHealth16,
    HomeHealth15,
    HomeHealth14,
    HomeHealth13,
    HomeHealth12,
    HomeHealth11,
    HomeHealth10,
    HomeHealth09,
    HomeHealth08,
    HomeHealth07,
    HomeHealth06,
    HomeHealth05,
)

from .hospital_inpatient_stays_models import (
    HospitalInpatientStays18,
    HospitalInpatientStays17,
    HospitalInpatientStays16,
    HospitalInpatientStays15,
    HospitalInpatientStays14,
    HospitalInpatientStays13,
    HospitalInpatientStays12,
    HospitalInpatientStays11,
    HospitalInpatientStays10,
    HospitalInpatientStays09,
    HospitalInpatientStays08,
    HospitalInpatientStays07,
    HospitalInpatientStays06,
    HospitalInpatientStays05,
)

from .medical_conditions_models import (
    MedicalConditions18,
    MedicalConditions17,
    MedicalConditions16,
    MedicalConditions15,
    MedicalConditions14,
    MedicalConditions13,
    MedicalConditions12,
    MedicalConditions11,
    MedicalConditions10,
    MedicalConditions09,
    MedicalConditions08,
    MedicalConditions07,
    MedicalConditions06,
    MedicalConditions05,
)

from .office_based_visits_models import (
    OfficeBasedVisits18,
    OfficeBasedVisits17,
    OfficeBasedVisits16,
    OfficeBasedVisits15,
    OfficeBasedVisits14,
    OfficeBasedVisits13,
    OfficeBasedVisits12,
    OfficeBasedVisits11,
    OfficeBasedVisits10,
    OfficeBasedVisits09,
    OfficeBasedVisits08,
    OfficeBasedVisits07,
    OfficeBasedVisits06,
    OfficeBasedVisits05,
)

from .other_medical_expenses_models import (
    OtherMedicalExpenses18,
    OtherMedicalExpenses17,
    OtherMedicalExpenses16,
    OtherMedicalExpenses15,
    OtherMedicalExpenses14,
    OtherMedicalExpenses13,
    OtherMedicalExpenses12,
    OtherMedicalExpenses11,
    OtherMedicalExpenses10,
    OtherMedicalExpenses09,
    OtherMedicalExpenses08,
    OtherMedicalExpenses07,
    OtherMedicalExpenses06,
    OtherMedicalExpenses05,
)

from .outpatient_visits_models import (
    OutpatientVisits18,
    OutpatientVisits17,
    OutpatientVisits16,
    OutpatientVisits15,
    OutpatientVisits14,
    OutpatientVisits13,
    OutpatientVisits12,
    OutpatientVisits11,
    OutpatientVisits10,
    OutpatientVisits09,
    OutpatientVisits08,
    OutpatientVisits07,
    OutpatientVisits06,
    OutpatientVisits05,
)

from .population_characteristics_models import (
    PopulationCharacteristics18,
    PopulationCharacteristics17,
    PopulationCharacteristics16,
    PopulationCharacteristics15,
    PopulationCharacteristics14,
    PopulationCharacteristics13,
    PopulationCharacteristics12,
    PopulationCharacteristics11,
    PopulationCharacteristics10,
    PopulationCharacteristics09,
    PopulationCharacteristics08,
    PopulationCharacteristics07,
    PopulationCharacteristics06,
    PopulationCharacteristics05,
)

from .prescribed_medicines_models import (
    PrescribedMedicines18,
    PrescribedMedicines17,
    PrescribedMedicines16,
    PrescribedMedicines15,
    PrescribedMedicines14,
    PrescribedMedicines13,
    PrescribedMedicines12,
    PrescribedMedicines11,
    PrescribedMedicines10,
    PrescribedMedicines09,
    PrescribedMedicines08,
    PrescribedMedicines07,
    PrescribedMedicines06,
    PrescribedMedicines05,
)
