from django.db import models

class DentalVisits18(models.Model):
    """ Defines the DentalVisits Model for 2018, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('PANEL # + ENCRYPTED DU IDENTIFIER',max_length=7)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=10)
    EVNTIDX = models.CharField('EVENT ID',max_length=16)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=14)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    GENDENT_M18 = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG_M18 = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DNSPCLST_M18 = models.CharField('DENTAL SPECIALIST SEEN',max_length=2)
    DENTYPE_M18 = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    PEDDENT_M18 = models.CharField('PEDIATRIC DENTIST SEEN',max_length=2)
    EXAMINE_M18 = models.CharField('GENERAL EXAM, CHECKUP OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH_M18',max_length=2)
    CLENTETH_M18 = models.CharField('CLEANING, PROPHYLAXIS, POLISHING OR PERIODONTAL RECALL',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY_M18',max_length=2)
    JUSTXRAY_M18 = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE_M18 = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANTX = models.CharField('EDITED SEALANT_M18',max_length=2)
    SEALANT_M18 = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING_M18',max_length=2)
    FILLING_M18 = models.CharField('FILLINGS, INLAYS, CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL_M18',max_length=2)
    ROOTCANL_M18 = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG_M18',max_length=2)
    GUMSURG_M18 = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM SURGERY',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT_M18',max_length=2)
    IMPLANT_M18 = models.CharField('IMPLANTS',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG_M18',max_length=2)
    ORALSURG_M18 = models.CharField('EXTRACTION, TOOTH PULLED OR OTH ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES_M18',max_length=2)
    BRIDGES_M18 = models.CharField('FIXED OR RELININGREPAIR OF BRIDGESDENTURES, REMOVABLE DENTURES',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT_M18',max_length=2)
    ORTHDONT_M18 = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('OTHER SPECIFY DENTAL PROCEDURES EDITED',max_length=25)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF18 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2018',max_length=3)
    FFTOT19 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2018',max_length=3)
    DVSF18X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR18X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD18X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    DVPV18X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA18X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR18X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF18X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL18X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC18X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR18X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU18X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT18X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP18X = models.CharField('SUM OF DVSF18X-DVOT18X (IMPUTED)',max_length=8)
    DVTC18X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT18F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2018',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2018',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2018',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits18 object"""
        return f"{self.DUPERSID}"

class DentalVisits17(models.Model):
    """ Defines the DentalVisits Model for 2017, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DNSPCLST = models.CharField('DENTAL SPECIALIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING,PROPHYLAXIS,POLISHINGRECAL VIS',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANTX = models.CharField('EDITED SEALANT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS, INLAYS, CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('EXTRACTION,TOOTH PULLEDOTH ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES,DENTURES,RELINREPAIR BRIDGDENT',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('OTHER SPECIFY DENTAL PROCEDURES EDITED',max_length=25)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF17 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2017',max_length=2)
    FFTOT18 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2017',max_length=2)
    DVSF17X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR17X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD17X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV17X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    DVVA17X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR17X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF17X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=6)
    DVSL17X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC17X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR17X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU17X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT17X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP17X = models.CharField('SUM OF DVSF17X-DVOT17X (IMPUTED)',max_length=8)
    DVTC17X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT17F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2017',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2017',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2017',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits17 object"""
        return f"{self.DUPERSID}"

class DentalVisits16(models.Model):
    """ Defines the DentalVisits Model for 2016, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('OTHER SPECIFY DENTAL PROCEDURES EDITED',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF16 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2016',max_length=2)
    FFTOT17 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2016',max_length=2)
    DVSF16X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR16X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD16X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV16X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA16X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR16X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=8)
    DVOF16X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL16X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=6)
    DVWC16X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR16X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU16X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT16X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP16X = models.CharField('SUM OF DVSF16X-DVOT16X (IMPUTED)',max_length=8)
    DVTC16X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT16F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2016',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2016',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2016',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits16 object"""
        return f"{self.DUPERSID}"

class DentalVisits15(models.Model):
    """ Defines the DentalVisits Model for 2015, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANTX = models.CharField('EDITED SEALANT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('OTHER SPECIFY DENTAL PROCEDURES EDITED',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF15 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2015',max_length=2)
    FFTOT16 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2015',max_length=2)
    DVSF15X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR15X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD15X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV15X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA15X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR15X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF15X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL15X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=6)
    DVWC15X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR15X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU15X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT15X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP15X = models.CharField('SUM OF DVSF15X-DVOT15X (IMPUTED)',max_length=8)
    DVTC15X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT15F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2015',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2015',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2015',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits15 object"""
        return f"{self.DUPERSID}"

class DentalVisits14(models.Model):
    """ Defines the DentalVisits Model for 2014, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIRX = models.CharField('EDITED REPAIR',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF14 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2014',max_length=2)
    FFTOT15 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2014',max_length=2)
    DVSF14X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR14X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD14X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV14X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA14X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR14X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF14X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL14X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC14X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    DVOR14X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU14X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT14X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP14X = models.CharField('SUM OF DVSF14X-DVOT14X (IMPUTED)',max_length=8)
    DVTC14X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT14F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2014',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2014',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2014',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits14 object"""
        return f"{self.DUPERSID}"

class DentalVisits13(models.Model):
    """ Defines the DentalVisits Model for 2013, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANTX = models.CharField('EDITED SEALANT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIRX = models.CharField('EDITED REPAIR',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF13 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2013',max_length=2)
    FFTOT14 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2013',max_length=2)
    DVSF13X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR13X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD13X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV13X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA13X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR13X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF13X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL13X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC13X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR13X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU13X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT13X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP13X = models.CharField('SUM OF DVSF13X-DVOT13X (IMPUTED)',max_length=8)
    DVTC13X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT13F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2013',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2013',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2013',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits13 object"""
        return f"{self.DUPERSID}"

class DentalVisits12(models.Model):
    """ Defines the DentalVisits Model for 2012, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF12 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2012',max_length=2)
    FFTOT13 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2012',max_length=2)
    DVSF12X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR12X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD12X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV12X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA12X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR12X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF12X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL12X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC12X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=4)
    DVOR12X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU12X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT12X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP12X = models.CharField('SUM OF DVSF12X-DVOT12X (IMPUTED)',max_length=8)
    DVTC12X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT12F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2012',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2012',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2012',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits12 object"""
        return f"{self.DUPERSID}"

class DentalVisits11(models.Model):
    """ Defines the DentalVisits Model for 2011, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    REPAIRX = models.CharField('EDITED REPAIR',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF11 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2011',max_length=2)
    FFTOT12 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2011',max_length=2)
    DVSF11X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR11X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD11X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV11X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    DVVA11X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=6)
    DVTR11X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF11X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL11X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC11X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR11X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU11X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT11X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP11X = models.CharField('SUM OF DVSF11X-DVOT11X (IMPUTED)',max_length=8)
    DVTC11X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT11F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2011',max_length=13)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2011',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2011',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits11 object"""
        return f"{self.DUPERSID}"

class DentalVisits10(models.Model):
    """ Defines the DentalVisits Model for 2010, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    REPAIRX = models.CharField('EDITED REPAIR',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF10 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2010',max_length=2)
    FFTOT11 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2010',max_length=2)
    DVSF10X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR10X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD10X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV10X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    DVVA10X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR10X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF10X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL10X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC10X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    DVOR10X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU10X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT10X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP10X = models.CharField('SUM OF DVSF10X-DVOT10X (IMPUTED)',max_length=8)
    DVTC10X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT10F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2010',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2010',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2010',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits10 object"""
        return f"{self.DUPERSID}"

class DentalVisits09(models.Model):
    """ Defines the DentalVisits Model for 2009, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    REPAIRX = models.CharField('EDITED REPAIR',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF09 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2009',max_length=2)
    FFTOT10 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2009',max_length=2)
    DVSF09X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR09X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD09X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV09X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA09X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR09X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF09X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL09X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC09X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    DVOR09X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU09X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT09X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP09X = models.CharField('SUM OF DVSF09X-DVOT09X (IMPUTED)',max_length=8)
    DVTC09X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT09F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2009',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2009',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2009',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits09 object"""
        return f"{self.DUPERSID}"

class DentalVisits08(models.Model):
    """ Defines the DentalVisits Model for 2008, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF08 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2008',max_length=2)
    FFTOT09 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2008',max_length=2)
    DVSF08X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR08X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD08X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV08X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    DVVA08X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA(IMPUTED)',max_length=7)
    DVTR08X = models.CharField('AMOUNT PAID, TRICARE(IMPUTED)',max_length=7)
    DVOF08X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL08X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC08X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR08X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU08X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=6)
    DVOT08X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP08X = models.CharField('SUM OF DVSF08X-DVOT08X (IMPUTED)',max_length=8)
    DVTC08X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT08F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2008',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2008',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2008',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits08 object"""
        return f"{self.DUPERSID}"

class DentalVisits07(models.Model):
    """ Defines the DentalVisits Model for 2007, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF07 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2007',max_length=2)
    FFTOT08 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2007',max_length=2)
    DVSF07X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    DVMR07X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD07X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV07X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    DVVA07X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    DVTR07X = models.CharField('AMOUNT PAID, TRICARECHAMPVA (IMPUTED)',max_length=7)
    DVOF07X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=6)
    DVSL07X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC07X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    DVOR07X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU07X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=6)
    DVOT07X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP07X = models.CharField('SUM OF DVSF07X-DVOT07X (IMPUTED)',max_length=8)
    DVTC07X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT07F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2007',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2007',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2007',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits07 object"""
        return f"{self.DUPERSID}"

class DentalVisits06(models.Model):
    """ Defines the DentalVisits Model for 2006, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF06 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2006',max_length=2)
    FFTOT07 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2006',max_length=2)
    DVSF06X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    DVMR06X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD06X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV06X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    DVVA06X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    DVTR06X = models.CharField('AMOUNT PAID, TRICARECHAMPVA (IMPUTED)',max_length=7)
    DVOF06X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL06X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC06X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    DVOR06X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU06X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    DVOT06X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP06X = models.CharField('SUM OF DVSF06X-DVOT06X (IMPUTED)',max_length=7)
    DVTC06X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=7)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT06F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2006',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2006',max_length=3)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2006',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits06 object"""
        return f"{self.DUPERSID}"

class DentalVisits05(models.Model):
    """ Defines the DentalVisits Model for 2005, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "DentalVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    DVDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    DVDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    DVDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    GENDENT = models.CharField('GENERAL DENTIST SEEN',max_length=2)
    DENTHYG = models.CharField('DENTAL HYGIENIST SEEN',max_length=2)
    DENTTECH = models.CharField('DENTAL TECHNICIAN SEEN',max_length=2)
    DENTSURG = models.CharField('DENTAL SURGEON SEEN',max_length=2)
    ORTHODNT = models.CharField('ORTHODONTIST SEEN',max_length=2)
    ENDODENT = models.CharField('ENDODONTIST SEEN',max_length=2)
    PERIODNT = models.CharField('PERIODONTIST SEEN',max_length=2)
    DENTYPE = models.CharField('OTHER DENTAL SPECIALIST SEEN',max_length=2)
    EXAMINE = models.CharField('GENERAL EXAM OR CONSULTATION',max_length=2)
    CLENTETX = models.CharField('EDITED CLENTETH',max_length=2)
    CLENTETH = models.CharField('CLEANING, PROPHYLAXIS, OR POLISHING',max_length=2)
    JUSTXRYX = models.CharField('EDITED JUSTXRAY',max_length=2)
    JUSTXRAY = models.CharField('X-RAYS, RADIOGRAPHS OR BITEWINGS',max_length=2)
    FLUORIDE = models.CharField('FLUORIDE TREATMENT',max_length=2)
    SEALANTX = models.CharField('EDITED SEALANT',max_length=2)
    SEALANT = models.CharField('SEALANT APPLICATION',max_length=2)
    FILLINGX = models.CharField('EDITED FILLING',max_length=2)
    FILLING = models.CharField('FILLINGS',max_length=2)
    INLAY = models.CharField('INLAYS',max_length=2)
    CROWNSX = models.CharField('EDITED CROWNS',max_length=2)
    CROWNS = models.CharField('CROWNS OR CAPS',max_length=2)
    ROOTCANX = models.CharField('EDITED ROOTCANL',max_length=2)
    ROOTCANL = models.CharField('ROOT CANAL',max_length=2)
    GUMSURGX = models.CharField('EDITED GUMSURG',max_length=2)
    GUMSURG = models.CharField('PERIODONTAL SCALING, ROOT PLANING OR GUM',max_length=2)
    RECLVISX = models.CharField('EDITED RECLVIS',max_length=2)
    RECLVIS = models.CharField('PERIODONTAL RECALL VISIT',max_length=2)
    EXTRACT = models.CharField('EXTRACTION, TOOTH PULLED',max_length=2)
    IMPLANTX = models.CharField('EDITED IMPLANT',max_length=2)
    IMPLANT = models.CharField('IMPLANTS',max_length=2)
    ABSCESS = models.CharField('ABSCESS OR INFECTION TREATMENT',max_length=2)
    ORALSURX = models.CharField('EDITED ORALSURG',max_length=2)
    ORALSURG = models.CharField('ORAL SURGERY',max_length=2)
    BRIDGESX = models.CharField('EDITED BRIDGES',max_length=2)
    BRIDGES = models.CharField('BRIDGES',max_length=2)
    DENTUREX = models.CharField('EDITED DENTURES',max_length=2)
    DENTURES = models.CharField('DENTURES OR PARTIAL DENTURES',max_length=2)
    REPAIR = models.CharField('REPAIR OF BRIDGESDENTURES OR RELINING',max_length=2)
    ORTHDONX = models.CharField('EDITED ORTHDONT',max_length=2)
    ORTHDONT = models.CharField('ORTHODONTIA, BRACES OR RETAINERS',max_length=2)
    WHITENX = models.CharField('EDITED WHITEN',max_length=2)
    WHITEN = models.CharField('BONDING, WHITENING, OR BLEACHING',max_length=2)
    TMDTMJ = models.CharField('TREATMENT FOR TMD OR TMJ',max_length=2)
    DENTPROX = models.CharField('EDITED DENTPROC',max_length=2)
    DENTPROC = models.CharField('OTHER DENTAL PROCEDURES',max_length=2)
    DENTOTHX = models.CharField('EDITED DENTOTHR',max_length=25)
    DENTOTHR = models.CharField('OTHER SPECIFIED DENTAL PROCEDURES',max_length=25)
    DENTMED = models.CharField('RECEIVED MEDICINE INCLUDING FREE SAMPLE',max_length=2)
    FFDVTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF05 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2005',max_length=2)
    FFTOT06 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2005',max_length=2)
    DVSF05X = models.CharField('AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    DVMR05X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    DVMD05X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    DVPV05X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    DVVA05X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    DVTR05X = models.CharField('HC-AMTPD, TRICARECHAMPVA (IMPUTED)',max_length=7)
    DVOF05X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    DVSL05X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    DVWC05X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    DVOR05X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    DVOU05X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=6)
    DVOT05X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    DVXP05X = models.CharField('SUM OF DVSF05X-DVOT05X (IMPUTED)',max_length=7)
    DVTC05X = models.CharField('HHLD REPORTED TOTAL CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT05F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2005',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2005',max_length=3)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2005',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a DentalVisits05 object"""
        return f"{self.DUPERSID}"
