from django.db import models

class OutpatientVisits18(models.Model):
    """ Defines the OutpatientVisits Model for 2018, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('PANEL # + ENCRYPTED DU IDENTIFIER',max_length=7)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=10)
    EVNTIDX = models.CharField('EVENT ID',max_length=16)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=14)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    SEEDOC_M18 = models.CharField('DID P TALK TO MD THIS VISIT',max_length=2)
    DRSPLTY_M18 = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE_M18 = models.CharField('TYPE OF MED PERSON P TALKED TO ON VISIT DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VISIT DT',max_length=3)
    VSTRELCN_M18 = models.CharField('THIS VISIT RELATED TO SPEC COND',max_length=2)
    LABTEST_M18 = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM_M18 = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS_M18 = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG_M18 = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI_M18 = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG_M18 = models.CharField('THIS VISIT DID P HAVE AN EKG, EEG OR ECG',max_length=2)
    RCVVAC_M18 = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF18 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2018',max_length=3)
    OPXP18X = models.CharField('TOTAL EXP FOR EVENT (OPFXP18X + OPDXP18X)',max_length=8)
    OPTC18X = models.CharField('TOTAL CHG FOR EVENT (OPFTC18X+OPDTC18X)',max_length=9)
    OPFSF18X = models.CharField('FACILITY AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    OPFMR18X = models.CharField('FACILITY AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    OPFMD18X = models.CharField('FACILITY AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    OPFPV18X = models.CharField('FACILITY AMOUNT PAID, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA18X = models.CharField('FACILITY AMOUNT PAID,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR18X = models.CharField('FACILITY AMOUNT PAID,TRICARE(IMPUTED)',max_length=7)
    OPFOF18X = models.CharField('FACILITY AMOUNT PAID, OTH FEDERAL (IMPUTED)',max_length=6)
    OPFSL18X = models.CharField('FACILITY AMOUNT PAID, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC18X = models.CharField('FACILITY AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR18X = models.CharField('FACILITY AMOUNT PAID, OTH PRIV (IMPUTED)',max_length=7)
    OPFOU18X = models.CharField('FACILITY AMOUNT PAID, OTH PUB (IMPUTED)',max_length=7)
    OPFOT18X = models.CharField('FACILITY AMOUNT PAID, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP18X = models.CharField('FACILITY SUM PAYMENTS OPFSF18X-OPFOT18X',max_length=8)
    OPFTC18X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF18X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR18X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD18X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV18X = models.CharField('DOCTOR AMOUNT PAID, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA18X = models.CharField('DOCTOR AMOUNT PAID,VETERANSCHAMPVA(IMPUTED)',max_length=7)
    OPDTR18X = models.CharField('DOCTOR AMOUNT PAID,TRICARE(IMPUTED)',max_length=7)
    OPDOF18X = models.CharField('DOCTOR AMOUNT PAID, OTH FEDERAL (IMPUTED)',max_length=4)
    OPDSL18X = models.CharField('DOCTOR AMOUNT PAID, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC18X = models.CharField('DOCTOR AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR18X = models.CharField('DOCTOR AMOUNT PAID, OTH PRIV (IMPUTED)',max_length=7)
    OPDOU18X = models.CharField('DOCTOR AMOUNT PAID, OTH PUB (IMPUTED)',max_length=6)
    OPDOT18X = models.CharField('DOCTOR AMOUNT PAID, OTH INSUR (IMPUTED)',max_length=8)
    OPDXP18X = models.CharField('DOCTOR SUM PAYMENTS OPDSF18X-OPDOT18X',max_length=8)
    OPDTC18X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT18F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2018',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2018',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2018',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits18 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits17(models.Model):
    """ Defines the OutpatientVisits Model for 2017, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG, EEG OR ECG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    OPXP17X = models.CharField('TOT EXP FOR EVENT (OPFXP17X + OPDXP17X)',max_length=9)
    OPTC17X = models.CharField('TOTAL CHG FOR EVENT (OPFTC17X+OPDTC17X)',max_length=10)
    OPFSF17X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR17X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD17X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV17X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA17X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR17X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=8)
    OPFOF17X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=6)
    OPFSL17X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC17X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=9)
    OPFOR17X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU17X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT17X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP17X = models.CharField('FACILITY SUM PAYMENTS OPFSF17X-OPFOT17X',max_length=9)
    OPFTC17X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=10)
    OPDSF17X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR17X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD17X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV17X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA17X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=7)
    OPDTR17X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF17X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL17X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC17X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR17X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=8)
    OPDOU17X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=6)
    OPDOT17X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP17X = models.CharField('DOCTOR SUM PAYMENTS OPDSF17X-OPDOT17X',max_length=8)
    OPDTC17X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT17F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2017',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2017',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2017',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits17 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits16(models.Model):
    """ Defines the OutpatientVisits Model for 2016, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF16 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2016',max_length=2)
    OPXP16X = models.CharField('TOT EXP FOR EVENT (OPFXP16X + OPDXP16X)',max_length=8)
    OPTC16X = models.CharField('TOTAL CHG FOR EVENT (OPFTC16X+OPDTC16X)',max_length=9)
    OPFSF16X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=7)
    OPFMR16X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD16X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV16X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA16X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR16X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=8)
    OPFOF16X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=7)
    OPFSL16X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC16X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPFOR16X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU16X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT16X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=7)
    OPFXP16X = models.CharField('FACILITY SUM PAYMENTS OPFSF16X-OPFOT16X',max_length=8)
    OPFTC16X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF16X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR16X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD16X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV16X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA16X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=7)
    OPDTR16X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF16X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL16X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=5)
    OPDWC16X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR16X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU16X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=7)
    OPDOT16X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP16X = models.CharField('DOCTOR SUM PAYMENTS OPDSF16X-OPDOT16X',max_length=8)
    OPDTC16X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=9)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT16F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2016',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2016',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2016',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits16 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits15(models.Model):
    """ Defines the OutpatientVisits Model for 2015, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFTOT16 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2015',max_length=2)
    OPXP15X = models.CharField('TOT EXP FOR EVENT (OPFXP15X + OPDXP15X)',max_length=8)
    OPTC15X = models.CharField('TOTAL CHG FOR EVENT (OPFTC15X+OPDTC15X)',max_length=9)
    OPFSF15X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR15X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD15X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV15X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA15X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR15X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=8)
    OPFOF15X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=8)
    OPFSL15X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC15X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPFOR15X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=7)
    OPFOU15X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=8)
    OPFOT15X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=7)
    OPFXP15X = models.CharField('FACILITY SUM PAYMENTS OPFSF15X-OPFOT15X',max_length=8)
    OPFTC15X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF15X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=8)
    OPDMR15X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD15X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV15X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA15X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=6)
    OPDTR15X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF15X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL15X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC15X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR15X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU15X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=7)
    OPDOT15X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP15X = models.CharField('DOCTOR SUM PAYMENTS OPDSF15X-OPDOT15X',max_length=8)
    OPDTC15X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT15F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2015',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2015',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2015',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits15 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits14(models.Model):
    """ Defines the OutpatientVisits Model for 2014, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF14 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2014',max_length=2)
    FFTOT15 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2014',max_length=2)
    OPXP14X = models.CharField('TOT EXP FOR EVENT (OPFXP14X + OPDXP14X)',max_length=8)
    OPTC14X = models.CharField('TOTAL CHG FOR EVENT (OPFTC14X+OPDTC14X)',max_length=9)
    OPFSF14X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR14X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD14X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV14X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA14X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR14X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPFOF14X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=7)
    OPFSL14X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC14X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR14X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU14X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=8)
    OPFOT14X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP14X = models.CharField('FACILITY SUM PAYMENTS OPFSF14X-OPFOT14X',max_length=8)
    OPFTC14X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF14X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR14X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    OPDMD14X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV14X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA14X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=7)
    OPDTR14X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF14X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL14X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC14X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR14X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU14X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=7)
    OPDOT14X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP14X = models.CharField('DOCTOR SUM PAYMENTS OPDSF14X-OPDOT14X',max_length=8)
    OPDTC14X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT14F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2014',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2014',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2014',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits14 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits13(models.Model):
    """ Defines the OutpatientVisits Model for 2013, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFTOT14 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2013',max_length=2)
    OPXP13X = models.CharField('TOT EXP FOR EVENT (OPFXP13X + OPDXP13X)',max_length=8)
    OPTC13X = models.CharField('TOTAL CHG FOR EVENT (OPFTC13X+OPDTC13X)',max_length=9)
    OPFSF13X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=7)
    OPFMR13X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD13X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV13X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA13X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR13X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPFOF13X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=7)
    OPFSL13X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=8)
    OPFWC13X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR13X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU13X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT13X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP13X = models.CharField('FACILITY SUM PAYMENTS OPFSF13X-OPFOT13X',max_length=8)
    OPFTC13X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF13X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR13X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD13X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV13X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA13X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=7)
    OPDTR13X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF13X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL13X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPDWC13X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR13X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU13X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=6)
    OPDOT13X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP13X = models.CharField('DOCTOR SUM PAYMENTS OPDSF13X-OPDOT13X',max_length=8)
    OPDTC13X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT13F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2013',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2013',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2013',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits13 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits12(models.Model):
    """ Defines the OutpatientVisits Model for 2012, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    OTHSHOT = models.CharField('THIS VISIT DID P HAVE OTHER SHOT',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPPRO2X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF12 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2012',max_length=2)
    OPXP12X = models.CharField('TOT EXP FOR EVENT (OPFXP12X + OPDXP12X)',max_length=9)
    OPTC12X = models.CharField('TOTAL CHG FOR EVENT (OPFTC12X+OPDTC12X)',max_length=9)
    OPFSF12X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR12X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD12X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=7)
    OPFPV12X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=9)
    OPFVA12X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR12X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPFOF12X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=8)
    OPFSL12X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC12X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR12X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=7)
    OPFOU12X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT12X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP12X = models.CharField('FACILITY SUM PAYMENTS OPFSF12X-OPFOT12X',max_length=9)
    OPFTC12X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF12X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR12X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD12X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV12X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA12X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=7)
    OPDTR12X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF12X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL12X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC12X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPDOR12X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU12X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=6)
    OPDOT12X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP12X = models.CharField('DOCTOR SUM PAYMENTS OPDSF12X-OPDOT12X',max_length=8)
    OPDTC12X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT12F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2012',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2012',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2012',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits12 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits11(models.Model):
    """ Defines the OutpatientVisits Model for 2011, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    OTHSHOT = models.CharField('THIS VISIT DID P HAVE OTHER SHOT',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPPRO2X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFTOT12 = models.CharField('NUMBER OF 2012 TOTAL EVENTS IN FLAT FEE',max_length=2)
    OPXP11X = models.CharField('TOT EXP FOR EVENT (OPFXP11X + OPDXP11X)',max_length=8)
    OPTC11X = models.CharField('TOTAL CHG FOR EVENT (OPFTC11X+OPDTC11X)',max_length=9)
    OPFSF11X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR11X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD11X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV11X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA11X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR11X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=8)
    OPFOF11X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=7)
    OPFSL11X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC11X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR11X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU11X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=8)
    OPFOT11X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP11X = models.CharField('FACILITY SUM PAYMENTS OPFSF11X-OPFOT11X',max_length=8)
    OPFTC11X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF11X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR11X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD11X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV11X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=8)
    OPDVA11X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=6)
    OPDTR11X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF11X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL11X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPDWC11X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR11X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU11X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=7)
    OPDOT11X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP11X = models.CharField('DOCTOR SUM PAYMENTS OPDSF11X-OPDOT11X',max_length=8)
    OPDTC11X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT11F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2011',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2011',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2011',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits11 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits10(models.Model):
    """ Defines the OutpatientVisits Model for 2010, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    OTHSHOT = models.CharField('THIS VISIT DID P HAVE OTHER SHOT',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPPRO2X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF10 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2010',max_length=2)
    OPXP10X = models.CharField('TOT EXP FOR EVENT (OPFXP10X + OPDXP10X)',max_length=8)
    OPTC10X = models.CharField('TOTAL CHG FOR EVENT (OPFTC10X+OPDTC10X)',max_length=9)
    OPFSF10X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR10X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD10X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV10X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA10X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR10X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=8)
    OPFOF10X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=8)
    OPFSL10X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=8)
    OPFWC10X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR10X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=7)
    OPFOU10X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT10X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP10X = models.CharField('FACILITY SUM PAYMENTS OPFSF10X-OPFOT10X',max_length=8)
    OPFTC10X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF10X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR10X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD10X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV10X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=7)
    OPDVA10X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=6)
    OPDTR10X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF10X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL10X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC10X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR10X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU10X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=7)
    OPDOT10X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP10X = models.CharField('DOCTOR SUM PAYMENTS OPDSF10X-OPDOT10X',max_length=7)
    OPDTC10X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT10F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2010',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2010',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2010',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits10 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits09(models.Model):
    """ Defines the OutpatientVisits Model for 2009, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    OTHSHOT = models.CharField('THIS VISIT DID P HAVE OTHER SHOT',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF09 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2009',max_length=2)
    FFTOT10 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2009',max_length=2)
    OPXP09X = models.CharField('TOT EXP FOR EVENT (OPFXP09X + OPDXP09X)',max_length=9)
    OPTC09X = models.CharField('TOTAL CHG FOR EVENT (OPFTC09X+OPDTC09X)',max_length=9)
    OPFSF09X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR09X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD09X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV09X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=9)
    OPFVA09X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR09X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPFOF09X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=6)
    OPFSL09X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=8)
    OPFWC09X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR09X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU09X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT09X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=7)
    OPFXP09X = models.CharField('FACILITY SUM PAYMENTS OPFSF09X-OPFOT09X',max_length=9)
    OPFTC09X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF09X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR09X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD09X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV09X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=7)
    OPDVA09X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=7)
    OPDTR09X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=6)
    OPDOF09X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL09X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPDWC09X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR09X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU09X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=7)
    OPDOT09X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP09X = models.CharField('DOCTOR SUM PAYMENTS OPDSF09X-OPDOT09X',max_length=7)
    OPDTC09X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT09F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2009',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2009',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2009',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits09 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits08(models.Model):
    """ Defines the OutpatientVisits Model for 2008, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    OTHSHOT = models.CharField('THIS VISIT DID P HAVE OTHER SHOT',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    THRTSWAB = models.CharField('THIS VISIT DID P HAVE A THROAT SWAB',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPPRO2X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF08 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2008',max_length=2)
    FFTOT09 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2008',max_length=2)
    OPXP08X = models.CharField('TOT EXP FOR EVENT (OPFXP08X + OPDXP08X)',max_length=8)
    OPTC08X = models.CharField('TOTAL CHG FOR EVENT (OPFTC08X+OPDTC08X)',max_length=8)
    OPFSF08X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=7)
    OPFMR08X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD08X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV08X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA08X = models.CharField('FAC AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=8)
    OPFTR08X = models.CharField('FACILITY AMT PD,TRICARE(IMPUTED)',max_length=8)
    OPFOF08X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=7)
    OPFSL08X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC08X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR08X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU08X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT08X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP08X = models.CharField('FACILITY SUM PAYMENTS OPFSF08X-OPFOT08X',max_length=8)
    OPFTC08X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=8)
    OPDSF08X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR08X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD08X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV08X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=7)
    OPDVA08X = models.CharField('DR AMT PD,VETERANSCHAMPVA(IMPUTED)',max_length=6)
    OPDTR08X = models.CharField('DOCTOR AMT PD,TRICARE(IMPUTED)',max_length=7)
    OPDOF08X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=6)
    OPDSL08X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPDWC08X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR08X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU08X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=6)
    OPDOT08X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=6)
    OPDXP08X = models.CharField('DOCTOR SUM PAYMENTS OPDSF08X-OPDOT08X',max_length=7)
    OPDTC08X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT08F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2008',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2008',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2008',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits08 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits07(models.Model):
    """ Defines the OutpatientVisits Model for 2007, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    OTHSHOT = models.CharField('THIS VISIT DID P HAVE OTHER SHOT',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    VAPLACE = models.CharField('VA FACILITY FLAG',max_length=1)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPPRO2X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFTOT08 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2007',max_length=2)
    OPXP07X = models.CharField('TOT EXP FOR EVENT (OPFXP07X + OPDXP07X)',max_length=8)
    OPTC07X = models.CharField('TOTAL CHG FOR EVENT (OPFTC07X+OPDTC07X)',max_length=8)
    OPFSF07X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR07X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD07X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=7)
    OPFPV07X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA07X = models.CharField('FACILITY AMT PD, VETERANS (IMPUTED)',max_length=8)
    OPFTR07X = models.CharField('FACILITY AMT PD,TRICARECHAMPVA(IMPUTED)',max_length=7)
    OPFOF07X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=7)
    OPFSL07X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=8)
    OPFWC07X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR07X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU07X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT07X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=8)
    OPFXP07X = models.CharField('FACILITY SUM PAYMENTS OPFSF07X-OPFOT07X',max_length=8)
    OPFTC07X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=8)
    OPDSF07X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR07X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD07X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV07X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=7)
    OPDVA07X = models.CharField('DOCTOR AMOUNT PAID, VETERANS (IMPUTED)',max_length=6)
    OPDTR07X = models.CharField('DOCTOR AMT PD, TRICARECHAMPVA (IMPUTED)',max_length=6)
    OPDOF07X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=6)
    OPDSL07X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC07X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPDOR07X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU07X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=6)
    OPDOT07X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP07X = models.CharField('DOCTOR SUM PAYMENTS OPDSF07X-OPDOT07X',max_length=8)
    OPDTC07X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT07F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2007',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2007',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2007',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits07 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits06(models.Model):
    """ Defines the OutpatientVisits Model for 2006, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=2)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    OTHSHOT = models.CharField('THIS VISIT DID P HAVE OTHER SHOT',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    VAPLACE = models.CharField('VA FACILITY FLAG',max_length=1)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPPRO2X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFTOT07 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2006',max_length=2)
    OPXP06X = models.CharField('TOT EXP FOR EVENT (OPFXP06X + OPDXP06X)',max_length=8)
    OPTC06X = models.CharField('TOTAL CHG FOR EVENT (OPFTC06X+OPDTC06X)',max_length=9)
    OPFSF06X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR06X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD06X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=8)
    OPFPV06X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA06X = models.CharField('FACILITY AMT PD, VETERANS (IMPUTED)',max_length=8)
    OPFTR06X = models.CharField('FACILITY AMT PD,TRICARECHAMPVA(IMPUTED)',max_length=7)
    OPFOF06X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=6)
    OPFSL06X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC06X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR06X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=7)
    OPFOU06X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT06X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=7)
    OPFXP06X = models.CharField('FACILITY SUM PAYMENTS OPFSF06X-OPFOT06X',max_length=8)
    OPFTC06X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF06X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR06X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    OPDMD06X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV06X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=7)
    OPDVA06X = models.CharField('DOCTOR AMOUNT PAID, VETERANS (IMPUTED)',max_length=6)
    OPDTR06X = models.CharField('DOCTOR AMT PD, TRICARECHAMPVA (IMPUTED)',max_length=6)
    OPDOF06X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL06X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=6)
    OPDWC06X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR06X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU06X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=7)
    OPDOT06X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP06X = models.CharField('DOCTOR SUM PAYMENTS OPDSF06X-OPDOT06X',max_length=8)
    OPDTC06X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT06F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2006',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2006',max_length=3)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2006',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits06 object"""
        return f"{self.DUPERSID}"

class OutpatientVisits05(models.Model):
    """ Defines the OutpatientVisits Model for 2005, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "OutpatientVisits"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    EVNTIDX = models.CharField('EVENT ID',max_length=12)
    EVENTRN = models.CharField('EVENT ROUND NUMBER',max_length=1)
    FFEEIDX = models.CharField('FLAT FEE ID',max_length=10)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    MPCDATA = models.CharField('MPC DATA FLAG',max_length=1)
    OPDATEYR = models.CharField('EVENT DATE - YEAR',max_length=4)
    OPDATEMM = models.CharField('EVENT DATE - MONTH',max_length=2)
    OPDATEDD = models.CharField('EVENT DATE - DAY',max_length=2)
    SEETLKPV = models.CharField('DID P VISIT PROV IN PERSON OR TELEPHONE',max_length=2)
    SEEDOC = models.CharField('DID P TALK TO MD THIS VISITPHONE CALL',max_length=2)
    DRSPLTY = models.CharField('OPAT DOCTOR S SPECIALTY',max_length=2)
    MEDPTYPE = models.CharField('TYPE OF MED PERSON P TALKED TO ON VST DT',max_length=2)
    VSTCTGRY = models.CharField('BEST CATEGORY FOR CARE P RECV ON VST DT',max_length=2)
    VSTRELCN = models.CharField('THIS VSTPHONE CALL RELATED TO SPEC COND',max_length=2)
    PHYSTH = models.CharField('THIS VISIT DID P HAVE PHYSICAL THERAPY',max_length=2)
    OCCUPTH = models.CharField('THIS VIS DID P HAVE OCCUPATIONAL THERAPY',max_length=2)
    SPEECHTH = models.CharField('THIS VISIT DID P HAVE SPEECH THERAPY',max_length=2)
    CHEMOTH = models.CharField('THIS VISIT DID P HAVE CHEMOTHERAPY',max_length=2)
    RADIATTH = models.CharField('THIS VISIT DID P HAVE RADIATION THERAPY',max_length=2)
    KIDNEYD = models.CharField('THIS VISIT DID P HAVE KIDNEY DIALYSIS',max_length=2)
    IVTHER = models.CharField('THIS VISIT DID P HAVE IV THERAPY',max_length=2)
    DRUGTRT = models.CharField('THIS VIS DID P HAVE TRT FOR DRUGALCOHOL',max_length=2)
    RCVSHOT = models.CharField('THIS VISIT DID P RECEIVE AN ALLERGY SHOT',max_length=2)
    PSYCHOTH = models.CharField('DID P HAVE PSYCHOTHERAPYCOUNSELING',max_length=2)
    LABTEST = models.CharField('THIS VISIT DID P HAVE LAB TESTS',max_length=2)
    SONOGRAM = models.CharField('THIS VISIT DID P HAVE SONOGRAM OR ULTRSD',max_length=2)
    XRAYS = models.CharField('THIS VISIT DID P HAVE X-RAYS',max_length=2)
    MAMMOG = models.CharField('THIS VISIT DID P HAVE A MAMMOGRAM',max_length=2)
    MRI = models.CharField('THIS VISIT DID P HAVE AN MRICATSCAN',max_length=2)
    EKG = models.CharField('THIS VISIT DID P HAVE AN EKG OR ECG',max_length=2)
    EEG = models.CharField('THIS VISIT DID P HAVE AN EEG',max_length=2)
    RCVVAC = models.CharField('THIS VISIT DID P RECEIVE A VACCINATION',max_length=2)
    ANESTH = models.CharField('THIS VISIT DID P RECEIVE ANESTHESIA',max_length=2)
    OTHSVCE = models.CharField('THIS VISIT DID P HAVE OTH DIAG TESTEXAM',max_length=2)
    SURGPROC = models.CharField('WAS SURG PROC PERFORMED ON P THIS VISIT',max_length=2)
    MEDPRESC = models.CharField('ANY MEDICINE PRESCRIBED FOR P THIS VISIT',max_length=2)
    VAPLACE = models.CharField('VA FACILITY FLAG',max_length=1)
    OPICD1X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD2X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD3X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPICD4X = models.CharField('3-DIGIT ICD-9-CM CONDITION CODE',max_length=3)
    OPPRO1X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPPRO2X = models.CharField('2-DIGIT ICD-9-CM PROCEDURE CODE',max_length=2)
    OPCCC1X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC2X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC3X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    OPCCC4X = models.CharField('MODIFIED CLINICAL CLASSIFICATION CODE',max_length=3)
    FFOPTYPE = models.CharField('FLAT FEE BUNDLE',max_length=2)
    FFBEF05 = models.CharField('TOTAL # OF VISITS IN FF BEFORE 2005',max_length=2)
    FFTOT06 = models.CharField('TOTAL # OF VISITS IN FF AFTER 2005',max_length=2)
    OPXP05X = models.CharField('TOT EXP FOR EVENT (OPFXP05X + OPDXP05X)',max_length=8)
    OPTC05X = models.CharField('TOTAL CHG FOR EVENT (OPFTC05X+OPDTC05X)',max_length=9)
    OPFSF05X = models.CharField('FACILITY AMT PD, FAMILY (IMPUTED)',max_length=8)
    OPFMR05X = models.CharField('FACILITY AMT PD, MEDICARE (IMPUTED)',max_length=8)
    OPFMD05X = models.CharField('FACILITY AMT PD, MEDICAID (IMPUTED)',max_length=7)
    OPFPV05X = models.CharField('FACILITY AMT PD, PRIV INSUR (IMPUTED)',max_length=8)
    OPFVA05X = models.CharField('FACILITY AMT PD, VETERANS (IMPUTED)',max_length=8)
    OPFTR05X = models.CharField('FACILITY AMT PD,TRICARECHAMPVA(IMPUTED)',max_length=7)
    OPFOF05X = models.CharField('FACILITY AMT PD, OTH FEDERAL (IMPUTED)',max_length=8)
    OPFSL05X = models.CharField('FACILITY AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPFWC05X = models.CharField('FACILITY AMT PD, WORKERS COMP (IMPUTED)',max_length=8)
    OPFOR05X = models.CharField('FACILITY AMT PD, OTH PRIV (IMPUTED)',max_length=8)
    OPFOU05X = models.CharField('FACILITY AMT PD, OTH PUB (IMPUTED)',max_length=7)
    OPFOT05X = models.CharField('FACILITY AMT PD, OTH INSUR (IMPUTED)',max_length=7)
    OPFXP05X = models.CharField('FACILITY SUM PAYMENTS OPFSF05X-OPFOT05X',max_length=8)
    OPFTC05X = models.CharField('TOTAL FACILITY CHARGE (IMPUTED)',max_length=9)
    OPDSF05X = models.CharField('DOCTOR AMOUNT PAID, FAMILY (IMPUTED)',max_length=7)
    OPDMR05X = models.CharField('DOCTOR AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    OPDMD05X = models.CharField('DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    OPDPV05X = models.CharField('DOCTOR AMT PD, PRIVATE INSUR (IMPUTED)',max_length=7)
    OPDVA05X = models.CharField('DOCTOR AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    OPDTR05X = models.CharField('DOCTOR AMT PD, TRICARECHAMPVA (IMPUTED)',max_length=6)
    OPDOF05X = models.CharField('DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)',max_length=5)
    OPDSL05X = models.CharField('DOCTOR AMT PD, STATELOC GOV (IMPUTED)',max_length=7)
    OPDWC05X = models.CharField('DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)',max_length=7)
    OPDOR05X = models.CharField('DOCTOR AMT PD, OTH PRIVATE (IMPUTED)',max_length=7)
    OPDOU05X = models.CharField('DOCTOR AMT PD, OTH PUBLIC (IMPUTED)',max_length=6)
    OPDOT05X = models.CharField('DOCTOR AMT PAID, OTH INSUR (IMPUTED)',max_length=7)
    OPDXP05X = models.CharField('DOCTOR SUM PAYMENTS OPDSF05X-OPDOT05X',max_length=7)
    OPDTC05X = models.CharField('TOTAL DOCTOR CHARGE (IMPUTED)',max_length=8)
    IMPFLAG = models.CharField('IMPUTATION STATUS',max_length=1)
    PERWT05F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2005',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2005',max_length=3)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2005',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a OutpatientVisits05 object"""
        return f"{self.DUPERSID}"

