from django.db import models

class PrescribedMedicines18(models.Model):
    """ Defines the PrescribedMedicines Model for 2018, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('PANEL # + ENCRYPTED DU IDENTIFIER',max_length=7)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=10)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=13)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=19)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=16)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=3)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICINE NAME (IMPUTED)',max_length=50)
    RXDRGNAM = models.CharField('MULTUM MEDICINE NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NDC (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=7)
    RXFORM = models.CharField('DOSAGE FORM (IMPUTED)',max_length=19)
    RXFRMUNT = models.CharField('QUANTITY UNIT OF MEDICATION (IMPUTED)',max_length=11)
    RXSTRENG = models.CharField('STRENGTH OF MEDICATION (IMPUTED)',max_length=11)
    RXSTRUNT = models.CharField('UNIT OF MEDICATION (IMPUTED)',max_length=11)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED (IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=3)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    PHARTP9 = models.CharField('TYPE OF PHARMACY PROV - 9TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    DIABEQUIP = models.CharField('OTHER DIABETIC EQUIPMENT OR SUPPLIES',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=3)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF18X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=8)
    RXMR18X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD18X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    RXPV18X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA18X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=8)
    RXTR18X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF18X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL18X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC18X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT18X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=8)
    RXOR18X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=8)
    RXOU18X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP18X = models.CharField('SUM OF PAYMENTS RXSF18X-RXOU18X(IMPUTED)',max_length=8)
    PERWT18F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2018',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2018',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2018',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines18 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines17(models.Model):
    """ Defines the PrescribedMedicines Model for 2017, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICINE NAME (IMPUTED)',max_length=50)
    RXDRGNAM = models.CharField('MULTUM MEDICINE NAME (IMPUTED)',max_length=47)
    RXNDC = models.CharField('NDC (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('DOSAGE FORM (IMPUTED)',max_length=19)
    RXFRMUNT = models.CharField('QUANTITY UNIT OF MEDICATION (IMPUTED)',max_length=12)
    RXSTRENG = models.CharField('STRENGTH OF MEDICATION (IMPUTED)',max_length=19)
    RXSTRUNT = models.CharField('UNIT OF MEDICATION (IMPUTED)',max_length=13)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    OMTYPE = models.CharField('OTHER MEDICAL EXPENSE TYPE',max_length=2)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF17X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR17X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD17X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    RXPV17X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA17X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=8)
    RXTR17X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=8)
    RXOF17X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL17X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=8)
    RXWC17X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    RXOT17X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    RXOR17X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=8)
    RXOU17X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP17X = models.CharField('SUM OF PAYMENTS RXSF17X-RXOU17X(IMPUTED)',max_length=8)
    PERWT17F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2017',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2017',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2017',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines17 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines16(models.Model):
    """ Defines the PrescribedMedicines Model for 2016, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICINE NAME (IMPUTED)',max_length=50)
    RXDRGNAM = models.CharField('MULTUM MEDICINE NAME (IMPUTED)',max_length=47)
    RXNDC = models.CharField('NDC (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('DOSAGE FORM (IMPUTED)',max_length=19)
    RXFRMUNT = models.CharField('QUANTITY UNIT OF MEDICATION (IMPUTED)',max_length=12)
    RXSTRENG = models.CharField('STRENGTH OF MEDICATION (IMPUTED)',max_length=12)
    RXSTRUNT = models.CharField('UNIT OF MEDICATION (IMPUTED)',max_length=13)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    PHARTP9 = models.CharField('TYPE OF PHARMACY PROV - 9TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    OMTYPE = models.CharField('OTHER MEDICAL EXPENSE TYPE',max_length=2)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF16X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR16X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD16X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    RXPV16X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA16X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=8)
    RXTR16X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=8)
    RXOF16X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL16X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC16X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT16X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    RXOR16X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=8)
    RXOU16X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP16X = models.CharField('SUM OF PAYMENTS RXSF16X-RXOU16X(IMPUTED)',max_length=8)
    PERWT16F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2016',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2016',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2016',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines16 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines15(models.Model):
    """ Defines the PrescribedMedicines Model for 2015, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICINE NAME (IMPUTED)',max_length=50)
    RXDRGNAM = models.CharField('MULTUM MEDICINE NAME (IMPUTED)',max_length=47)
    RXNDC = models.CharField('NDC (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('DOSAGE FORM (IMPUTED)',max_length=12)
    RXFRMUNT = models.CharField('QUANTITY UNIT OF MEDICATION (IMPUTED)',max_length=12)
    RXSTRENG = models.CharField('STRENGTH OF MEDICATION (IMPUTED)',max_length=10)
    RXSTRUNT = models.CharField('UNIT OF MEDICATION (IMPUTED)',max_length=11)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    OMTYPE = models.CharField('OTHER MEDICAL EXPENSE TYPE',max_length=2)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF15X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=8)
    RXMR15X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD15X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    RXPV15X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA15X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=7)
    RXTR15X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF15X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL15X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC15X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT15X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    RXOR15X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=8)
    RXOU15X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP15X = models.CharField('SUM OF PAYMENTS RXSF15X-RXOU15X(IMPUTED)',max_length=8)
    PERWT15F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2015',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2015',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2015',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines15 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines14(models.Model):
    """ Defines the PrescribedMedicines Model for 2014, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICINE NAME (IMPUTED)',max_length=50)
    RXDRGNAM = models.CharField('MULTUM MEDICINE NAME (IMPUTED)',max_length=47)
    RXNDC = models.CharField('NDC (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('DOSAGE FORM (IMPUTED)',max_length=12)
    RXFRMUNT = models.CharField('QUANTITY UNIT OF MEDICATION (IMPUTED)',max_length=12)
    RXSTRENG = models.CharField('STRENGTH OF MEDICATION (IMPUTED)',max_length=11)
    RXSTRUNT = models.CharField('UNIT OF MEDICATION (IMPUTED)',max_length=11)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    OMTYPE = models.CharField('OTHER MEDICAL EXPENSE TYPE',max_length=2)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF14X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR14X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD14X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    RXPV14X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA14X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=8)
    RXTR14X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF14X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL14X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC14X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    RXOT14X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=6)
    RXOR14X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    RXOU14X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP14X = models.CharField('SUM OF PAYMENTS RXSF14X-RXOU14X(IMPUTED)',max_length=8)
    PERWT14F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2014',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2014',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2014',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines14 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines13(models.Model):
    """ Defines the PrescribedMedicines Model for 2013, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICINE NAME (IMPUTED)',max_length=50)
    RXDRGNAM = models.CharField('MULTUM MEDICINE NAME (IMPUTED)',max_length=44)
    RXNDC = models.CharField('NDC (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('DOSAGE FORM (IMPUTED)',max_length=28)
    RXFRMUNT = models.CharField('QUANTITY UNIT OF MEDICATION (IMPUTED)',max_length=11)
    RXSTRENG = models.CharField('STRENGTH OF MEDICATION (IMPUTED)',max_length=9)
    RXSTRUNT = models.CharField('UNIT OF MEDICATION (IMPUTED)',max_length=11)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, RX CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF13X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR13X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD13X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    RXPV13X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA13X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=7)
    RXTR13X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF13X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=6)
    RXSL13X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC13X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT13X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=6)
    RXOR13X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=8)
    RXOU13X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP13X = models.CharField('SUM OF PAYMENTS RXSF13X-RXOU13X(IMPUTED)',max_length=8)
    PERWT13F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2013',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2013',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2013',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines13 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines12(models.Model):
    """ Defines the PrescribedMedicines Model for 2012, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGDD = models.CharField('DAY PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=9)
    RXFORM = models.CharField('FORM OF RXPRESCRIBED MEDICINE (IMPUTED)',max_length=12)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RXPRESC MED (IMPUTED)',max_length=12)
    RXSTRENG = models.CharField('STRENGTH OF RXPRESCR MED DOSE (IMPUTED)',max_length=10)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF RX (IMPUTED)',max_length=13)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    PHARTP9 = models.CharField('TYPE OF PHARMACY PROV - 9TH',max_length=2)
    PHARTP10 = models.CharField('TYPE OF PHARMACY PROV - 10TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, RX CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF12X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=8)
    RXMR12X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD12X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    RXPV12X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA12X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=8)
    RXTR12X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF12X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL12X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=8)
    RXWC12X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT12X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    RXOR12X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    RXOU12X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP12X = models.CharField('SUM OF PAYMENTS RXSF12X-RXOU12X(IMPUTED)',max_length=8)
    PERWT12F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2012',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2012',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2012',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines12 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines11(models.Model):
    """ Defines the PrescribedMedicines Model for 2011, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RXPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGDD = models.CharField('DAY PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=9)
    RXFORM = models.CharField('FORM OF RXPRESCRIBED MEDICINE (IMPUTED)',max_length=28)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RXPRESC MED (IMPUTED)',max_length=5)
    RXSTRENG = models.CharField('STRENGTH OF RXPRESCR MED DOSE (IMPUTED)',max_length=10)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF RX (IMPUTED)',max_length=11)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    IMPFLAG = models.CharField('METHOD OF EXPENDITURE DATA CREATION',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, RX CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF11X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR11X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD11X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    RXPV11X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA11X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=7)
    RXTR11X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF11X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL11X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC11X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT11X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    RXOR11X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    RXOU11X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP11X = models.CharField('SUM OF PAYMENTS RXSF11X-RXOU11X(IMPUTED)',max_length=8)
    PERWT11F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2011',max_length=13)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2011',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2011',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines11 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines10(models.Model):
    """ Defines the PrescribedMedicines Model for 2010, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RxPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGDD = models.CharField('DAY PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=44)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=9)
    RXFORM = models.CharField('FORM OF RXPRESCRIBED MEDICINE (IMPUTED)',max_length=28)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RXPRESC MED (IMPUTED)',max_length=5)
    RXSTRENG = models.CharField('STRENGTH OF RXPRESCR MED DOSE (IMPUTED)',max_length=11)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF RX (IMPUTED)',max_length=11)
    RXDAYSUP = models.CharField('DAYS SUPPLIED OF PRESCRIBED MED(IMPUTED)',max_length=3)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, RX CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF10X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR10X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD10X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=8)
    RXPV10X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA10X = models.CharField('AMOUNT PAID, VETERANSCHAMPVA (IMPUTED)',max_length=8)
    RXTR10X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF10X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=8)
    RXSL10X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC10X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    RXOT10X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    RXOR10X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    RXOU10X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP10X = models.CharField('SUM OF PAYMENTS RXSF10X-RXOU10X(IMPUTED)',max_length=8)
    PERWT10F = models.CharField('EXPENDITURE FILE PERSON WEIGHT, 2010',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2010',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2010',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines10 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines09(models.Model):
    """ Defines the PrescribedMedicines Model for 2009, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    DRUGIDX = models.CharField('DRUG ID (DUPERSID + COUNTER)',max_length=11)
    RXRECIDX = models.CharField('UNIQUE RxPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RXPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGDD = models.CharField('DAY PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RXPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('FORM OF RXPRESCRIBED MEDICINE (IMPUTED)',max_length=29)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RXPRESC MED (IMPUTED)',max_length=5)
    RXSTRENG = models.CharField('STRENGTH OF RXPRESCR MED DOSE (IMPUTED)',max_length=27)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF RX (IMPUTED)',max_length=14)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, RX CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF RX IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF09X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR09X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD09X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    RXPV09X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    RXVA09X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    RXTR09X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF09X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL09X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC09X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT09X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=7)
    RXOR09X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    RXOU09X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP09X = models.CharField('SUM OF PAYMENTS RXSF09X-RXOU09X(IMPUTED)',max_length=8)
    PERWT09F = models.CharField('FINAL PERSON LEVEL WEIGHT, 2009',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2009',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2009',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines09 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines08(models.Model):
    """ Defines the PrescribedMedicines Model for 2008, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    RXRECIDX = models.CharField('UNIQUE RxPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RxPRESCR MED OBTAINEDPURCHASED',max_length=1)
    DUP2007 = models.CharField('DUPLICATE ACQUISITION ON 2007 PMED FILE',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RxPRESCR MED (IMPUTED)',max_length=9)
    RXFORM = models.CharField('FORM OF RxPRESCRIBED MEDICINE (IMPUTED)',max_length=9)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RxPRESC MED (IMPUTED)',max_length=2)
    RXSTRENG = models.CharField('STRENGTH OF RxPRESCR MED DOSE (IMPUTED)',max_length=14)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF Rx (IMPUTED)',max_length=13)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    PHARTP9 = models.CharField('TYPE OF PHARMACY PROV - 9TH',max_length=2)
    PHARTP10 = models.CharField('TYPE OF PHARMACY PROV - 10TH',max_length=2)
    PHARTP11 = models.CharField('TYPE OF PHARMACY PROV - 11TH',max_length=2)
    PHARTP12 = models.CharField('TYPE OF PHARMACY PROV - 12TH',max_length=2)
    PHARTP13 = models.CharField('TYPE OF PHARMACY PROV - 13TH',max_length=2)
    PHARTP14 = models.CharField('TYPE OF PHARMACY PROV - 14TH',max_length=2)
    PHARTP15 = models.CharField('TYPE OF PHARMACY PROV - 15TH',max_length=2)
    PHARTP16 = models.CharField('TYPE OF PHARMACY PROV - 16TH',max_length=2)
    PHARTP17 = models.CharField('TYPE OF PHARMACY PROV - 17TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, Rx CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF Rx IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    RXSF08X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR08X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    RXMD08X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    RXPV08X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    RXVA08X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    RXTR08X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=6)
    RXOF08X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=7)
    RXSL08X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC08X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT08X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=6)
    RXOR08X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    RXOU08X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=7)
    RXXP08X = models.CharField('SUM OF PAYMENTS RXSF08X-RXOU08X(IMPUTED)',max_length=7)
    PERWT08F = models.CharField('FINAL PERSON LEVEL WEIGHT, 2008',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2008',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2008',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines08 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines07(models.Model):
    """ Defines the PrescribedMedicines Model for 2007, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    RXRECIDX = models.CharField('UNIQUE RxPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RxPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RxPRESCR MED (IMPUTED)',max_length=9)
    RXFORM = models.CharField('FORM OF RxPRESCRIBED MEDICINE (IMPUTED)',max_length=10)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RxPRESC MED (IMPUTED)',max_length=2)
    RXSTRENG = models.CharField('STRENGTH OF RxPRESCR MED DOSE (IMPUTED)',max_length=14)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF Rx (IMPUTED)',max_length=13)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    PHARTP9 = models.CharField('TYPE OF PHARMACY PROV - 9TH',max_length=2)
    PHARTP10 = models.CharField('TYPE OF PHARMACY PROV - 10TH',max_length=2)
    PHARTP11 = models.CharField('TYPE OF PHARMACY PROV - 11TH',max_length=2)
    PHARTP12 = models.CharField('TYPE OF PHARMACY PROV - 12TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, Rx CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF Rx IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    RXSF07X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR07X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=7)
    RXMD07X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    RXPV07X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    RXVA07X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    RXTR07X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF07X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=6)
    RXSL07X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=7)
    RXWC07X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=7)
    RXOT07X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=6)
    RXOR07X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=7)
    RXOU07X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=6)
    RXXP07X = models.CharField('SUM OF PAYMENTS RXSF07X-RXOU07X(IMPUTED)',max_length=7)
    PERWT07F = models.CharField('FINAL PERSON LEVEL WEIGHT, 2007',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2007',max_length=4)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2007',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines07 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines06(models.Model):
    """ Defines the PrescribedMedicines Model for 2006, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    RXRECIDX = models.CharField('UNIQUE RxPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RxPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGDD = models.CharField('DAY PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RxPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('FORM OF RxPRESCRIBED MEDICINE (IMPUTED)',max_length=14)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RxPRESC MED (IMPUTED)',max_length=2)
    RXSTRENG = models.CharField('STRENGTH OF RxPRESCR MED DOSE (IMPUTED)',max_length=17)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF Rx (IMPUTED)',max_length=17)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, Rx CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF Rx IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF06X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR06X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=8)
    RXMD06X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    RXPV06X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=8)
    RXVA06X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    RXTR06X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF06X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=6)
    RXSL06X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=6)
    RXWC06X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    RXOT06X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=6)
    RXOR06X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=6)
    RXOU06X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=6)
    RXXP06X = models.CharField('SUM OF PAYMENTS RXSF06X-RXOU06X(IMPUTED)',max_length=8)
    PERWT06F = models.CharField('FINAL PERSON LEVEL WEIGHT, 2006',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2006',max_length=3)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2006',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines06 object"""
        return f"{self.DUPERSID}"

class PrescribedMedicines05(models.Model):
    """ Defines the PrescribedMedicines Model for 2005, derived from the model class. """

    # Metadata
    class Meta:
        """ Set parameters for admin app"""
        ordering = ['DUPERSID']
        verbose_name_plural = "PrescribedMedicines"
    DUID = models.CharField('DWELLING UNIT ID',max_length=5)
    PID = models.CharField('PERSON NUMBER',max_length=3)
    DUPERSID = models.CharField('PERSON ID (DUID + PID)',max_length=8)
    RXRECIDX = models.CharField('UNIQUE RxPRESCRIBED MEDICINE IDENTIFIER',max_length=15)
    LINKIDX = models.CharField('ID FOR LINKAGE TO CONDOTH EVENT FILES',max_length=12)
    PANEL = models.CharField('PANEL NUMBER',max_length=2)
    PURCHRD = models.CharField('ROUND RxPRESCR MED OBTAINEDPURCHASED',max_length=1)
    RXBEGDD = models.CharField('DAY PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGMM = models.CharField('MONTH PERSON STARTED TAKING MEDICINE',max_length=2)
    RXBEGYRX = models.CharField('YEAR PERSON STARTED TAKING MEDICINE',max_length=4)
    RXNAME = models.CharField('MEDICATION NAME (IMPUTED)',max_length=50)
    RXNDC = models.CharField('NATIONAL DRUG CODE (IMPUTED)',max_length=11)
    RXQUANTY = models.CharField('QUANTITY OF RxPRESCR MED (IMPUTED)',max_length=8)
    RXFORM = models.CharField('FORM OF RxPRESCRIBED MEDICINE (IMPUTED)',max_length=12)
    RXFRMUNT = models.CharField('UNIT OF MEAS FORM RxPRESC MED (IMPUTED)',max_length=2)
    RXSTRENG = models.CharField('STRENGTH OF RxPRESCR MED DOSE (IMPUTED)',max_length=17)
    RXSTRUNT = models.CharField('UNIT OF MEAS STRENGTH OF Rx (IMPUTED)',max_length=14)
    PHARTP1 = models.CharField('TYPE OF PHARMACY PROV - 1ST',max_length=2)
    PHARTP2 = models.CharField('TYPE OF PHARMACY PROV - 2ND',max_length=2)
    PHARTP3 = models.CharField('TYPE OF PHARMACY PROV - 3RD',max_length=2)
    PHARTP4 = models.CharField('TYPE OF PHARMACY PROV - 4TH',max_length=2)
    PHARTP5 = models.CharField('TYPE OF PHARMACY PROV - 5TH',max_length=2)
    PHARTP6 = models.CharField('TYPE OF PHARMACY PROV - 6TH',max_length=2)
    PHARTP7 = models.CharField('TYPE OF PHARMACY PROV - 7TH',max_length=2)
    PHARTP8 = models.CharField('TYPE OF PHARMACY PROV - 8TH',max_length=2)
    PHARTP9 = models.CharField('TYPE OF PHARMACY PROV - 9TH',max_length=2)
    RXFLG = models.CharField('NDC IMPUTATION SOURCE ON PC DONOR REC',max_length=1)
    PCIMPFLG = models.CharField('TYPE OF HC TO PC PRESCRIPTION MATCH',max_length=1)
    CLMOMFLG = models.CharField('CHGEPYMNT, Rx CLAIM FILING, OMTYPE STAT',max_length=1)
    INPCFLG = models.CharField('PID HAS AT LEAST 1 RECORD IN PC',max_length=1)
    SAMPLE = models.CharField('HOUSEHLD RCVD FREE SAMPLE OF Rx IN ROUND',max_length=1)
    RXICD1X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD2X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXICD3X = models.CharField('3 DIGIT ICD-9 CONDITION CODE',max_length=3)
    RXCCC1X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC2X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    RXCCC3X = models.CharField('MODIFIED CLINICAL CLASS CODE',max_length=3)
    PREGCAT = models.CharField('MULTUM PREGNANCY CATEGORY',max_length=2)
    TC1 = models.CharField('MULTUM THERAPEUTIC CLASS #1',max_length=3)
    TC1S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC1',max_length=3)
    TC1S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S1',max_length=3)
    TC1S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC1',max_length=3)
    TC1S2_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S2',max_length=3)
    TC1S3 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #3 FOR TC1',max_length=2)
    TC1S3_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC1S3',max_length=2)
    TC2 = models.CharField('MULTUM THERAPEUTIC CLASS #2',max_length=3)
    TC2S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC2',max_length=3)
    TC2S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S1_2 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC2S1',max_length=3)
    TC2S2 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #2 FOR TC2',max_length=3)
    TC3 = models.CharField('MULTUM THERAPEUTIC CLASS #3',max_length=3)
    TC3S1 = models.CharField('MULTUM THERAPEUTIC SUB-CLASS #1 FOR TC3',max_length=3)
    TC3S1_1 = models.CharField('MULTUM THERAPEUT SUB-SUB-CLASS FOR TC3S1',max_length=3)
    RXSF05X = models.CharField('AMOUNT PAID, SELF OR FAMILY (IMPUTED)',max_length=7)
    RXMR05X = models.CharField('AMOUNT PAID, MEDICARE (IMPUTED)',max_length=6)
    RXMD05X = models.CharField('AMOUNT PAID, MEDICAID (IMPUTED)',max_length=7)
    RXPV05X = models.CharField('AMOUNT PAID, PRIVATE INSURANCE (IMPUTED)',max_length=7)
    RXVA05X = models.CharField('AMOUNT PAID, VETERANS (IMPUTED)',max_length=7)
    RXTR05X = models.CharField('AMOUNT PAID, TRICARE (IMPUTED)',max_length=7)
    RXOF05X = models.CharField('AMOUNT PAID, OTHER FEDERAL (IMPUTED)',max_length=6)
    RXSL05X = models.CharField('AMOUNT PAID, STATE & LOCAL GOV (IMPUTED)',max_length=6)
    RXWC05X = models.CharField('AMOUNT PAID, WORKERS COMP (IMPUTED)',max_length=6)
    RXOT05X = models.CharField('AMOUNT PAID, OTHER INSURANCE (IMPUTED)',max_length=6)
    RXOR05X = models.CharField('AMOUNT PAID, OTHER PRIVATE (IMPUTED)',max_length=6)
    RXOU05X = models.CharField('AMOUNT PAID, OTHER PUBLIC (IMPUTED)',max_length=6)
    RXXP05X = models.CharField('SUM OF PAYMENTS RXSF05X-RXOU05X(IMPUTED)',max_length=7)
    PERWT05F = models.CharField('FINAL PERSON LEVEL WEIGHT, 2005',max_length=12)
    VARSTR = models.CharField('VARIANCE ESTIMATION STRATUM, 2005',max_length=3)
    VARPSU = models.CharField('VARIANCE ESTIMATION PSU, 2005',max_length=1)

    # Methods
    def __str__(self):
        """String for representing a PrescribedMedicines05 object"""
        return f"{self.DUPERSID}"

